"""Builds docs/mockups/kit/icons.js from the app's own icons.

Every component of src/ui/icons.rs becomes an inline SVG, plus the Phosphor
icons kept in docs/mockups/kit/phosphor/ for what the app does not draw yet.
Run it again whenever icons.rs changes.
"""

import glob
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ICONS_RS = os.path.join(ROOT, "src/ui/icons.rs")
KIT = os.path.join(ROOT, "docs/mockups/kit")
CHILD = r"(?:path|circle|rect|line|polyline|polygon|ellipse|g)"


def attrs(block):
    return " ".join(
        '%s="%s"' % ("viewBox" if k == "view_box" else k.replace("_", "-"), v)
        for k, v in re.findall(r'(\w+):\s*"([^"]*)"', block)
        if k not in ("width", "height")
    )


def app_icons(src):
    out = {}
    for name, body in re.findall(r"pub fn (\w+)\b[^\n]*-> Element \{\s*rsx! \{(.*?)\n\}\n", src, re.S):
        svg = re.search(r"svg \{(.*?)\n\s*" + CHILD + r" \{", body, re.S)
        if not svg:
            continue
        children = "".join(
            "<%s %s/>" % (tag, attrs(block))
            for tag, block in re.findall(r"\b(" + CHILD[3:-1] + r") \{([^{}]*)\}", body)
        )
        out[name] = '<svg %s width="SIZE" height="SIZE">%s</svg>' % (attrs(svg.group(1)), children)
    return out


def phosphor_icons():
    out = {}
    for path in sorted(glob.glob(os.path.join(KIT, "phosphor", "*.svg"))):
        stem = os.path.basename(path)[:-4]
        name = "Ph" + "".join(part.capitalize() for part in stem.split("-"))
        svg = open(path).read().strip()
        out[name] = svg.replace('<svg xmlns="http://www.w3.org/2000/svg"', '<svg width="SIZE" height="SIZE"')
    return out


def main():
    icons = app_icons(open(ICONS_RS).read())
    icons.update(phosphor_icons())
    with open(os.path.join(KIT, "icons.js"), "w") as f:
        f.write("// Generated by scripts/mockup_icons.py, do not edit.\n")
        f.write("window.ICONS = " + json.dumps(icons, indent=0) + ";\n")
    print("%d icons -> docs/mockups/kit/icons.js" % len(icons))


if __name__ == "__main__":
    main()
