"""Builds docs/mockups/kit/icons.js from the app's own icons.

Every Icon* and *Glyph component under src/ui becomes an inline SVG, plus
the Phosphor icons kept in docs/mockups/kit/phosphor/ for what the app does
not draw yet.
Run scripts/mockups.sh whenever the app icons change.
"""

import glob
import json
import os
import re

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
UI = os.path.join(ROOT, "src/ui")
KIT = os.path.join(ROOT, "docs/mockups/kit")
CHILD = r"(?:path|circle|rect|line|polyline|polygon|ellipse|g)"


def attrs(block):
    return " ".join(
        '%s="%s"' % ("viewBox" if k == "view_box" else k.replace("_", "-"), v)
        for k, v in re.findall(r'(\w+):\s*"([^"]*)"', block)
        if k not in ("width", "height")
    )


def app_icons(src):
    out = {}
    pattern = r"fn (Icon\w+|\w+Glyph)\b[^\n]*-> Element \{\s*rsx! \{(.*?)\n\}\n"
    for name, body in re.findall(pattern, src, re.S):
        svg = re.search(r"svg \{(.*?)\n\s*" + CHILD + r" \{", body, re.S)
        if not svg:
            continue
        children = "".join(
            "<%s %s/>" % (tag, attrs(block))
            for tag, block in re.findall(r"\b(" + CHILD[3:-1] + r") \{([^{}]*)\}", body)
        )
        out[name] = '<svg %s width="SIZE" height="SIZE">%s</svg>' % (attrs(svg.group(1)), children)
    return out


def phosphor_icons():
    out = {}
    for path in sorted(glob.glob(os.path.join(KIT, "phosphor", "*.svg"))):
        stem = os.path.basename(path)[:-4]
        name = "Ph" + "".join(part.capitalize() for part in stem.split("-"))
        svg = open(path).read().strip()
        out[name] = svg.replace('<svg xmlns="http://www.w3.org/2000/svg"', '<svg width="SIZE" height="SIZE"')
    return out


def main():
    sources = glob.glob(os.path.join(UI, "**", "*.rs"), recursive=True)
    icons = {}
    for path in sorted(sources):
        icons.update(app_icons(open(path).read()))
    icons.update(phosphor_icons())
    with open(os.path.join(KIT, "icons.js"), "w") as f:
        f.write("// Generated by scripts/mockup_icons.py, do not edit.\n")
        f.write("window.ICONS = " + json.dumps(icons, indent=0) + ";\n")
    print("%d icons -> docs/mockups/kit/icons.js" % len(icons))


if __name__ == "__main__":
    main()
